version: '3'

networks:
  default:
    ipam:
      config:
        - subnet: 200.0.0.0/16
services:
  db_app3:
    image: mongo
    restart: always
    environment:
      MONGODB_DATABASE: metrics
    volumes:
        - /data/app3/db:/data/db
    ports:
        - 27018:27017
  server_app3:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    command: python server.py
    restart: on-failure
    depends_on:
      - db_app3
    links:
      - db_app3
