version: '3'

networks:
  default:
    ipam:
      config:
        - subnet: 20.0.0.0/16
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGODB_DATABASE: metrics
    volumes:
        - /data/app3/db:/data/db
    ports:
        - 27018:27017
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    command: python server.py
    restart: on-failure
    depends_on:
      - db
    links:
      - db
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: python client.py
    restart: on-failure
    depends_on:
      - server
    links:
      - server