# Metricas das vms
groups:
  - name: uso_cpu
    rules:
    - record: node_exporter:uso_cpu
      expr: 100 - (avg (irate(node_cpu_seconds_total{node_exporter="nodeexporter",mode="idle"})) by (instance) * 100)

  - name: uso_memoria
    rules:
    - record: node_exporter:uso_memoria
      expr: 100 - 100 * (node_memory_MemFree / node_memory_MemTotal)

  - name: bytes_rx
    rules:
    - record  : node_exporter:bytes_rx
      expr: sum (irate(node_network_receive_bytes_total)) by (instance)

  - name: bytes_tx
    rules:
    - record: node_exporter:bytes_tx
      expr: sum (irate(node_network_transmit_bytes_total)) by (instance)
