global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
monitor: 'docker-host-alpha'



# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - 'app2_rules.yml'
  - 'app3_rules.yml'

scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.50.2:9100', '192.168.50.3:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.50.2:8080', '192.168.50.3:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
- targets: ['localhost:9090']
