version: '3'

networks:
  default:
    ipam:
      config:
        - subnet: 10.0.0.0/16
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGODB_DATABASE: metrics
    volumes:
        - /data/app2/db:/data/db
    ports:
        - 27017:27017
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    command: python server.py
    restart: on-failure
    depends_on:
      - db
    links:
      - db
