version: '3'

networks:
  default:
    ipam:
      config:
        - subnet: 100.0.0.0/16
services:
  db_app2:
    image: mongo
    restart: always
    environment:
      MONGODB_DATABASE: metrics
    volumes:
        - /data/app2/db:/data/db
    ports:
        - 27017:27017
  server_app2:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: python server.py
    restart: on-failure
    depends_on:
      - db_app2
    links:
      - db_app2
